apiVersion: v1
kind: Service
metadata:
  name: elearning-service
spec:
  selector:
    app: elearning
    version: blue  # Initially points to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
